// <auto-generated />
namespace SmartClinic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _10FixTableIdentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_10FixTableIdentity));
        
        string IMigrationMetadata.Id
        {
            get { return "201804270104401_1.0-Fix-Table-Identity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
