// <auto-generated />
namespace SmartClinic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _10_change_appointment_time_to_timespan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_10_change_appointment_time_to_timespan));
        
        string IMigrationMetadata.Id
        {
            get { return "201804231614088_1.0_change_appointment_time_to_timespan"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
